In [ ]:
# For data manipulation
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)
import io

Mounted at /content/gdrive

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/train.csv')

In [ ]:
df.head()

,Deal_title,Lead_name,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Contact_no,Lead_revenue,Fund_category,...,Designation,Lead_POC_email,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,"Davis, Perkins and Bishop Inc",Restaurants,320506$,2067263.7$,2020-03-29,Product_2,607.447.7883,50 - 100 Million,Category 2,...,Executive Vice President,charlenewerner@davis.com,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",NaN,3,73.6
1,TitleKIW18,Bender PLC LLC,Construction Services,39488$,240876.8$,2019-07-10,Product_2,892-938-9493,500 Million - 1 Billion,Category 4,...,Chairman/CEO/President,terrylogan@bender.com,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
2,TitleFXSDN,Carter-Henry and Sons,Hospitals/Clinics,359392$,2407926.4$,2019-07-27,Product_1,538.748.2271,500 Million - 1 Billion,Category 4,...,SVP/General Counsel,arielhamilton@carterhenry.com,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Garcia Ltd Ltd,Real Estate,76774$,468321.4$,2021-01-30,Product_2,(692)052-1389x75188,500 Million - 1 Billion,Category 3,...,CEO/Co-Founder/Chairman,erinwilson@garcia.com,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
4,Title904GV,Lee and Sons PLC,Financial Services,483896$,NaN,2019-05-22,Product_2,001-878-814-6134x015,50 - 100 Million,Category 3,...,Executive Vice President,mr.christopher@lee.com,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [ ]:
#checking dataframe columns
df.columns

Index(['Deal_title', 'Lead_name', 'Industry', 'Deal_value', 'Weighted_amount',
       'Date_of_creation', 'Pitch', 'Contact_no', 'Lead_revenue',
       'Fund_category', 'Geography', 'Location', 'POC_name', 'Designation',
       'Lead_POC_email', 'Hiring_candidate_role', 'Lead_source',
       'Level_of_meeting', 'Last_lead_update', 'Internal_POC', 'Resource',
       'Internal_rating', 'Success_probability'],
      dtype='object')

In [ ]:
df.shape

(7007, 23)

In [ ]:
#checking the unique values to decide which value is to be dropped
len(df.Lead_name.unique())

7007

In [ ]:
len(df.Date_of_creation	.unique())

777

In [ ]:
len(df.Internal_POC	.unique())

60

In [ ]:
#dropping the columns that are not required for modelling
df1= df.drop(["Lead_name","Contact_no","POC_name","Lead_POC_email"], axis=1)

In [ ]:
df1.head()

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,Restaurants,320506$,2067263.7$,2020-03-29,Product_2,50 - 100 Million,Category 2,USA,"Killeen-Temple, TX",Executive Vice President,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",NaN,3,73.6
1,TitleKIW18,Construction Services,39488$,240876.8$,2019-07-10,Product_2,500 Million - 1 Billion,Category 4,India,Ratlam,Chairman/CEO/President,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
2,TitleFXSDN,Hospitals/Clinics,359392$,2407926.4$,2019-07-27,Product_1,500 Million - 1 Billion,Category 4,USA,"Albany-Schenectady-Troy, NY",SVP/General Counsel,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Real Estate,76774$,468321.4$,2021-01-30,Product_2,500 Million - 1 Billion,Category 3,USA,"Mount Vernon-Anacortes, WA",CEO/Co-Founder/Chairman,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
4,Title904GV,Financial Services,483896$,NaN,2019-05-22,Product_2,50 - 100 Million,Category 3,India,Shimoga,Executive Vice President,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [ ]:
#checking for missing values
df1.isnull().sum()

Deal_title                 0
Industry                   1
Deal_value                51
Weighted_amount          525
Date_of_creation           0
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                972
Location                  11
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         633
Internal_POC               0
Resource                 149
Internal_rating            0
Success_probability        0
dtype: int64

In [ ]:
df1[df1["Industry"].isnull()]

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
4653,Title232C0,NaN,209418$,1266978.9$,2020-12-15,Product_2,50 - 100 Million,Category 4,India,Pilibhit,SVP/General Counsel,Landscape architect,Contact Email,Level 1,2 days back,"Hameier,Kurt E",No,3,56.6

In [ ]:
#replacing the missing values and replacing it with mode
df1["Industry"] = df1["Industry"].fillna((df1["Industry"].mode()[0]))

In [ ]:
df1[df1["Deal_value"].isnull()]

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
169,TitleKXH1L,Banks,NaN,1023175.8$,2020-06-12,Product_2,50 - 100 Million,Category 2,USA,"Panama City, FL",Chairman/Chief Innovation Officer,Information officer,Others,Level 1,Up-to-date,"Cashin,Marc C",Cannot deliver,4,66.90
381,TitleBV4VN,Iron/Steel,NaN,668538.0$,2019-08-24,Product_2,100 - 500 Million,Category 1,India,Akola,Executive Vice President,Insurance account manager,Others,Level 2,No track,"Dunaway,Antoine",Yes,1,60.40
448,TitleMUK48,Real Estate,NaN,NaN,2020-05-23,Product_2,100 - 500 Million,Category 2,India,Alipurduar,Chairman/CEO/President,Optometrist,Website,Level 1,NaN,"Shelton,Sidney P",No,3,62.70
469,TitleXSNO6,Software,NaN,1167666.85$,2020-05-19,Product_1,500 Million - 1 Billion,Category 1,India,Bhagalpur,Chairman/CEO/President,Minerals surveyor,Contact Email,Level 3,No track,"Moran,Natalie A",We have all the requirements,2,63.20
519,TitleK69MY,Banks,NaN,2839513.6$,2020-07-25,Product_1,100 - 500 Million,Category 4,India,Haora,Executive Vice President,Restaurant manager,Website,Level 3,5 days back,"Houston,Arnold E",Deliverable,1,61.90
1016,TitleXD5MP,Network Infrastructure,NaN,2929018.9$,2019-05-26,Product_1,500 Million - 1 Billion,Category 1,India,Amritsar,SVP/General Counsel,"Civil engineer, consulting",Marketing Event,Level 2,?,"Bannister,Joan",Deliverable,4,67.00
1148,TitleWB44B,Furniture/Fixtures,NaN,2432947.95$,2020-10-27,Product_2,500 Million - 1 Billion,Category 4,USA,"Bellingham, WA",SVP/General Counsel,Community pharmacist,Contact Email,Level 3,Following up but lead not responding,"Hanyok,John J",We have all the requirements,4,69.90
1246,Title6X0QM,Staffing,NaN,1195450.0$,2019-08-19,Product_1,50 - 100 Million,Category 4,India,Rampura,Executive Vice President,Primary school teacher,Marketing Event,Level 2,Up-to-date,"Brown,Maxine A",Deliverable,2,58.40
1328,TitleDUHSS,Insurance,NaN,2607096.45$,2020-01-31,Product_2,50 - 100 Million,Category 4,India,Bharauri,CEO/President,Bonds trader,Others,Level 1,No track,"Van Arter,Derrick",Not enough,2,54.70
1587,TitleMPX29,Music,NaN,408901.35$,2020-03-22,Product_1,50 - 100 Million,Category 2,USA,"Ann Arbor, MI",CEO/President,"Designer, textile",Marketing Event,Level 2,More than a week back,"Vickers Jr.,Henry J",Not enough,4,107.34
1599,Title27F7I,Education/Training,NaN,224107.9$,2019-09-27,Product_2,500 Million - 1 Billion,Category 4,India,Jabalpur,CEO/President,Sports administrator,Marketing Event,Level 1,Following up but lead not responding,"Brown,Maxine A",No,1,55.60
1626,TitleO80HC,Apparel Retail,NaN,1059562.4$,2019-02-21,Product_2,100 - 500 Million,Category 4,USA,"Santa Maria-Santa Barbara, CA",Chairman/CEO/President,Health promotion specialist,Marketing Event,Level 1,Pending,"Maine,John P",Not enough,5,69.50
1636,TitleNSRAK,Banks,NaN,2748051.2$,2020-08-19,Product_1,500 Million - 1 Billion,Category 2,USA,"Bellingham, WA",Executive Vice President,Associate Professor,Marketing Event,Level 1,Did not hear back after Level 1,"Hebron,Artenia D",We have all the requirements,5,72.90
1651,TitleSGTCT,Real Estate,NaN,66601.6$,2020-08-09,Product_1,500 Million - 1 Billion,Category 2,India,Krishnanagar,Vice President / GM (04-present) : VP Sales an...,Printmaker,Others,Level 1,Did not hear back after Level 1,"Himes,Maurice C",Yes,2,55.60
1849,Title8XSJJ,Other,NaN,1455981.2$,2021-02-06,Product_1,500 Million - 1 Billion,Category 1,USA,"Salisbury, MD-DE",SVP/General Counsel,Chief Financial Officer,Others,Level 3,more than a month,"Davis,Brian R",Yes,3,74.70
1943,Title62ICV,Electronics,NaN,1666770.6$,2019-08-23,Product_1,100 - 500 Million,Category 1,India,Saharanpur,CEO/Chairman/President,"Nurse, adult",Marketing Event,Level 2,more than a month,"Cash,Tyrone J",Yes,4,26.35
2039,TitleXQ4QR,Banks,NaN,3295175.4$,2020-09-09,Product_1,50 - 100 Million,Category 1,USA,"Florence-Muscle Shoals, AL",SVP/General Counsel,Interpreter,Contact Email,Level 3,No track,"Pappas,Mark S",We have all the requirements,1,68.30
2165,TitlePC79J,Banks,NaN,1936548.25$,2020-12-19,Product_2,500 Million - 1 Billion,Category 2,India,Rajapalaiyam,Chairman/CEO/President,Insurance claims handler,Website,Level 1,?,"Tondeur,Keith D",Not enough,2,60.90
2241,TitleIUOP5,Banks,NaN,1190311.85$,2019-03-16,Product_1,100 - 500 Million,Category 1,USA,"Jacksonville, NC",Chairman/CEO/President,Restaurant manager,Others,Level 3,NaN,"Massiah,Gerard F",Not enough,1,70.10
2469,TitleTYPR7,Financial Services,NaN,2139806.85$,2019-01-28,Product_1,50 - 100 Million,Category 4,USA,"Weirton-Steubenville, WV-OH",Chairman/Chief Innovation Officer,"Embryologist, clinical",Others,Level 2,?,"Jones,Eyvette W",Cannot deliver,5,68.70
2487,TitleDGY3M,Recreational Services,NaN,1469188.05$,2019-09-26,Product_1,50 - 100 Million,Category 3,USA,"Midland, TX",SVP/General Counsel,Clinical cytogeneticist,Contact Email,Level 1,more than a month,"Vickers Jr.,Henry J",Cannot deliver,5,66.20
2869,TitleZZXEA,Movies,NaN,1977882.7$,2020-10-20,Product_2,500 Million - 1 Billion,Category 4,USA,"Jackson, TN",CEO/President,"Engineer, maintenance (IT)",Contact Email,Level 3,Up-to-date,"Pappas,Mark S",Yes,1,107.34
2953,TitleFF3TA,Medical Equipment,NaN,1482643.25$,2019-06-22,Product_2,100 - 500 Million,Category 2,India,Puri,SVP/General Counsel,Fast food restaurant manager,Others,Level 3,More than a week back,"McKenstry,Loretta A",No,4,64.80
3139,TitleGUEIA,Insurance,NaN,2055754.4$,2020-09-27,Product_1,500 Million - 1 Billion,Category 1,India,Mathura,Executive Vice President,"Surveyor, planning and development",Contact Email,Level 3,?,"Georgakopoulos,Vasilios T",Deliverable,2,63.20
3272,TitleAXESK,Staffing,NaN,2263868.6$,2020-12-29,Product_1,100 - 500 Million,Category 2,India,Mangalore,SVP/General Counsel,Professor Emeritus,Marketing Event,Level 2,No track,"Ullrich,Rose Anne",Cannot deliver,3,26.35
3327,TitleNMDJA,Hospitals/Clinics,NaN,2498082.0$,2019-04-07,Product_1,50 - 100 Million,Category 1,NaN,Silchar,CEO/Co-Founder/Chairman,"Surveyor, commercial/residential",Marketing Event,Level 3,NaN,"Abdul-Hamid,Saud Muhamad",Cannot deliver,3,67.80
3403,TitleZELYQ,Banks,NaN,NaN,2020-08-02,Product_2,100 - 500 Million,Category 2,USA,"Detroit-Warren-Dearborn, MI",Executive Vice President,Broadcast presenter,Contact Email,Level 1,More than 2 weeks,"Shelton,Sidney P",Yes,1,62.90
3586,Title83O8F,Restaurants,NaN,2694762.5$,2020-07-07,Product_2,100 - 500 Million,Category 2,NaN,Rohtak,Chairman/CEO/President,Podiatrist,Website,Level 2,Up-to-date,"Dyson,William A",Cannot deliver,5,66.50
3632,TitleZFOVB,"Oil, Gas, Coal",NaN,1851598.35$,2019-09-13,Product_2,500 Million - 1 Billion,Category 2,India,Aurangabad,Chairman/Chief Innovation Officer,"Designer, blown glass/stained glass",Others,Level 3,5 days back,"Himes,Maurice C",Deliverable,1,63.00
3919,TitleRWOK0,Other,NaN,2485949.55$,2020-02-03,Product_2,500 Million - 1 Billion,Category 3,USA,"Amarillo, TX",Executive Vice President,Interior and spatial designer,Others,Level 3,NaN,"Gaskins Jr,Franklin D",We have all the requirements,5,73.80
4269,Title8T56L,Banks,NaN,3175824.4$,2020-08-12,Product_1,500 Million - 1 Billion,Category 4,USA,"Greenville, NC",Chairman/CEO/President,Animal nutritionist,Contact Email,Level 3,more than a month,"Hameier,Kurt E",We have all the requirements,1,66.70
4300,TitleQLI4G,Software,NaN,1865694.6$,2020-08-07,Product_1,500 Million - 1 Billion,Category 2,USA,"Corvallis, OR",CEO/President,Charity officer,Marketing Event,Level 2,Pending,"Ryker,David",NaN,5,74.60
4722,TitleFWISC,Insurance,NaN,NaN,2020-12-05,Product_1,50 - 100 Million,Category 3,India,Rajkot,Chairman/CEO/President,Best boy,Others,Level 2,No track,"Mabrey,Kevin C",Cannot deliver,1,53.90
4745,TitleMLDBZ,Food Processing,NaN,232377.0$,2020-10-08,Product_2,100 - 500 Million,Category 4,India,Alwar,CEO/Co-Founder/Chairman,Recruitment consultant,Others,Level 1,5 days back,"Hebron,Artenia D",Deliverable,3,55.40
4926,Title371LP,Non-Profit,NaN,1744578.0$,2019-06-07,Product_2,100 - 500 Million,Category 4,USA,"Muskegon, MI",CEO/Chairman/President,Magazine features editor,Contact Email,Level 2,Did not hear back after Level 1,"Gilley,Janine",Cannot deliver,3,65.80
5276,TitleVMPZG,Other Biz Services,NaN,1339298.3$,2020-09-10,Product_2,500 Million - 1 Billion,Category 4,NaN,"Rochester, MN",CEO/Chairman/President,Hotel manager,Others,Level 3,More than 2 weeks,"Hameier,Kurt E",Yes,4,71.20
5401,Title1DHCN,Lending/Mortgage,NaN,1711770.8$,2019-08-20,Product_2,50 - 100 Million,Category 1,USA,"Pine Bluff, AR",Executive Vice President,"Librarian, academic",Contact Email,Level 3,5 days back,"Green,Candy",Cannot deliver,3,26.35
5451,Title49N0C,Financial Services,NaN,NaN,2019-12-07,Product_1,500 Million - 1 Billion,Category 4,India,Kalyan,CEO/President,Chartered accountant,Website,Level 2,Did not hear back after Level 1,"Featherstone,Adrian R",Not enough,1,107.34
5620,TitleL45YI,Banks,NaN,96495.75$,2019-04-07,Product_2,500 Million - 1 Billion,Category 3,India,Silchar,Chairman/Chief Innovation Officer,"Teacher, secondary school",Others,Level 3,2 days back,"Green,Ann E",We have all the requirements,2,107.34
5889,TitleCA8OV,Financial Services,NaN,799571.2$,2019-01-13,Product_1,100 - 500 Million,Category 1,USA,"Springfield, MO",Executive Vice President,"Doctor, hospital",Marketing Event,Level 2,Did not hear back after Level 1,"Murray,Younetta",We have all the requirements,3,72.60
6001,TitleJ28M7,Retail,NaN,1701722.25$,2019-10-15,Product_2,100 - 500 Million,Category 1,USA,"San Luis Obispo-Paso Robles-Arroyo Grande, CA",CEO/Co-Founder/Chairman,Health service manager,Contact Email,Level 3,Following up but lead not responding,"Booker,David L",No,1,68.80
6100,TitleEUOPL,Banks,NaN,150485.4$,2019-07-06,Product_1,100 - 500 Million,Category 2,NaN,Ranchi,SVP/General Counsel,Proofreader,Marketing Event,Level 2,Pending,"Himes,Maurice C",Deliverable,4,61.10
6115,TitleZCNWC,Trucking,NaN,2210982.4$,2019-06-17,Product_2,50 - 100 Million,Category 3,USA,"Missoula, MT",Chief Executive Officer,English as a foreign language teacher,Others,Level 3,2 days back,"Himes,Maurice C",Cannot deliver,5,71.90
6213,Title43EZV,Investment Bank/Brokerage,NaN,448921.35$,2019-02-23,Product_2,500 Million - 1 Billion,Category 4,USA,"Burlington, NC",Chairman/CEO/President,Higher education careers adviser,Marketing Event,Level 3,No track,"Houston,Arnold E",Deliverable,1,68.00
6423,TitleNBT4E,Sales/Marketing Services,NaN,823636.65$,2019-03-05,Product_2,50 - 100 Million,Category 2,USA,"Tuscaloosa, AL",Chairman/CEO/President,Media planner,Others,Level 1,Did not hear back after Level 1,"Mabrey,Kevin C",No,3,66.90
6501,Title445PS,"Oil, Gas, Coal",NaN,2227864.8$,2019-01-06,Product_2,500 Million - 1 Billion,Category 2,NaN,"Savannah, GA",Chairman/Chief Innovation Officer,"Programme researcher, broadcasting/film/video",Others,Level 1,More than a week back,"Green,Candy",Not enough,2,26.35
6567,Title1P6RF,Insurance,NaN,2259299.65$,2021-01-05,Product_2,50 - 100 Million,Category 2,India,Asansol,CEO/President,Physiotherapist,Others,Level 1,Up-to-date,"Houston,Arnold E",We have all the requirements,4,59.90
6611,TitleRFVSJ,Security Services,NaN,532115.65$,2020-01-02,Product_2,500 Million - 1 Billion,Category 3,India,Bengaluru,Executive Vice President,"Biochemist, clinical",Website,Level 1,?,"Gould,Lisa D",We have all the requirements,3,62.60
6653,TitleODFVR,Healthcare Facilities/Services,NaN,1106557.2$,2019-09-06,Product_1,50 - 100 Million,Category 2,NaN,"Bloomington, IL",Chairman/CEO/President,Medical sales representative,Contact Email,Level 3,NaN,"Meli,Teresa V",We have all the requirements,3,70.00
6878,TitleJ8EL1,Real Estate,NaN,2063642.9$,2019-09-07,Product_2,500 Million - 1 Billion,Category 3,India,Imphal,CEO/President,Technical author,Website,Level 2,More than 2 weeks,"Himes,Maurice C",Cannot deliver,2,61.10
6885,Title8JHPF,Banks,NaN,2141010.45$,2020-06-05,Product_2,100 - 500 Million,Category 4,USA,"Elkhart-Goshen, IN",CEO/Co-Founder/Chairman,Biomedical engineer,Website,Level 1,Following up but lead not responding,"Moran,Natalie A",We have all the requirements,2,107.34

In [ ]:
df1["Deal_value"]= df1["Deal_value"].str.replace("$","")
df1.Deal_value.head()

<ipython-input-628-8d0cd6edcd96>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1["Deal_value"]= df1["Deal_value"].str.replace("$","")

0    320506
1     39488
2    359392
3     76774
4    483896
Name: Deal_value, dtype: object

In [ ]:
#converting Deal_Value to numeric
df1["Deal_value"] = pd.to_numeric(df1["Deal_value"])
#imputing missing value in Deal_value
df1["Deal_value"] = df1["Deal_value"].fillna(df1["Deal_value"].mean())

In [ ]:
df1[df1["Weighted_amount"].isnull()]

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
4,Title904GV,Financial Services,483896.0,NaN,2019-05-22,Product_2,50 - 100 Million,Category 3,India,Shimoga,Executive Vice President,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.40
13,TitleNQKU6,Banks,487351.0,NaN,2020-04-25,Product_1,500 Million - 1 Billion,Category 3,NaN,Pilibhit,Chairman/Chief Innovation Officer,Hospital doctor,Marketing Event,Level 3,More than a week back,"Shelton,Sidney P",We have all the requirements,2,26.35
17,TitleEWIQD,Software,140949.0,NaN,2019-05-19,Product_1,100 - 500 Million,Category 3,USA,"Columbus, IN",Executive Vice President,Phytotherapist,Marketing Event,Level 2,More than a week back,"Mabrey,Kevin C",Yes,1,66.40
23,TitleO0W9A,REIT,207335.0,NaN,2020-10-27,Product_1,100 - 500 Million,Category 3,India,Ahmadnagar,CEO/Chairman/President,Warden/ranger,Website,Level 2,More than a week back,"Irizarry,Yolanda",Yes,4,62.90
33,TitleQ5K7M,Automotive/Transportation,335694.0,NaN,2019-10-04,Product_2,50 - 100 Million,Category 3,USA,"Chico, CA",CEO/President,Operational investment banker,Contact Email,Level 1,Did not hear back after Level 1,"Morsy,Omar A",Yes,3,64.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6971,Title6SSU1,Hospitals/Clinics,101621.0,NaN,2019-05-14,Product_1,50 - 100 Million,Category 1,USA,"Madison, WI",CEO,Clinical biochemist,Marketing Event,Level 3,NaN,"Irizarry,Yolanda",We have all the requirements,4,74.80
6975,Title5441H,Financial Services,456307.0,NaN,2020-04-03,Product_2,500 Million - 1 Billion,Category 2,India,Gangtok,CEO/Chairman/President,Travel agency manager,Marketing Event,Level 2,5 days back,"Ali,Mohamed",Deliverable,4,65.50
6983,TitleVDKHN,Professional Services,89949.0,NaN,2019-07-07,Product_1,100 - 500 Million,Category 2,NaN,"Grand Forks, ND-MN",SVP/General Counsel,Volunteer coordinator,Website,Level 1,NaN,"Charles,Caleb",Deliverable,3,69.70
6990,Title4H88W,Insurance,240326.0,NaN,2020-11-23,Product_2,100 - 500 Million,Category 4,India,Muzaffarnagar,Executive Vice President,"Lecturer, higher education",Contact Email,Level 1,Following up but lead not responding,"Featherstone,Adrian R",No,1,53.90
7004,TitleF1FWY,Semiconductors,253608.0,NaN,2020-03-10,Product_1,100 - 500 Million,Category 2,USA,"Rocky Mount, NC",SVP/General Counsel,Nature conservation officer,Marketing Event,Level 3,NaN,"Logan,Kevin N",NaN,1,70.60

In [ ]:
# removing the $ sign
df1["Weighted_amount"]= df1["Weighted_amount"].str.replace("$","")
#converting Weighted_amount to numeric
df1["Weighted_amount"] = pd.to_numeric(df1["Weighted_amount"])
df1["Weighted_amount"] = df1["Weighted_amount"].fillna(df1["Weighted_amount"].mean())

<ipython-input-631-456722094f97>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1["Weighted_amount"]= df1["Weighted_amount"].str.replace("$","")

In [ ]:
#converting the Date_of_creation to date time
df1["Date_of_creation"] = pd.to_datetime(df1["Date_of_creation"])
df1.Date_of_creation.dtype

dtype('<M8[ns]')

In [ ]:
df1[df1["Geography"].isnull()].head()

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
6,TitleOZQRY,Banks,384356.0,2.709710e+06,2019-11-20,Product_2,500 Million - 1 Billion,Category 1,NaN,"Salisbury, MD-DE",CEO/Co-Founder/Chairman,Cartographer,Contact Email,Level 3,More than 2 weeks,"Booker,David L",NaN,4,73.40
10,TitleP5EAQ,Healthcare Facilities/Services,311125.0,1.851194e+06,2020-01-30,Product_1,500 Million - 1 Billion,Category 2,NaN,"Oxnard-Thousand Oaks-Ventura, CA",CEO/Co-Founder/Chairman,Hydrogeologist,Website,Level 1,Following up but lead not responding,"Clavey,Therese A",Cannot deliver,2,67.90
13,TitleNQKU6,Banks,487351.0,1.569884e+06,2020-04-25,Product_1,500 Million - 1 Billion,Category 3,NaN,Pilibhit,Chairman/Chief Innovation Officer,Hospital doctor,Marketing Event,Level 3,More than a week back,"Shelton,Sidney P",We have all the requirements,2,26.35
16,TitleBZ8I3,Other Investment Firms,390309.0,2.458947e+06,2019-10-13,Product_2,50 - 100 Million,Category 2,NaN,"Miami-Fort Lauderdale-West Palm Beach, FL",Chairman/CEO/President,Broadcast journalist,Contact Email,Level 3,?,"Dimattia,Frank D",Deliverable,4,70.00
27,TitleWKMYP,Trucking,380817.0,2.513392e+06,2019-05-31,Product_2,50 - 100 Million,Category 1,NaN,"Chambersburg-Waynesboro, PA",CEO/President,Armed forces operational officer,Contact Email,Level 3,Did not hear back after Level 1,"Leu,Darren L",No,1,68.30

In [ ]:
df1.isnull().sum()

Deal_title                 0
Industry                   0
Deal_value                 0
Weighted_amount            0
Date_of_creation           0
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                972
Location                  11
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         633
Internal_POC               0
Resource                 149
Internal_rating            0
Success_probability        0
dtype: int64

In [ ]:
df1.Location = df1.Location.fillna('Other')

In [ ]:
df1.isnull().sum()

Deal_title                 0
Industry                   0
Deal_value                 0
Weighted_amount            0
Date_of_creation           0
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                972
Location                   0
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         633
Internal_POC               0
Resource                 149
Internal_rating            0
Success_probability        0
dtype: int64

In [ ]:
# df1["Geography"] = df1["Geography"].fillna((df1["Geography"].mode()[0]))
def state_USA(s):
    return s[-2:]
def state_USA2(s):
    return s[-2:]
USA_states_taken_from_WWW = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "OR", "DE", "FL",
                             "GA", "HI" , "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME",
                             "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH",
                             "NJ", "NM", "NY", "NC", "ND", "OH", "OK", 'PA', 'RI', 'SC',
                             'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI',"WY"]
def state(state):
  if state in USA_states_taken_from_WWW:
    return "USA"
  else:
    return "India"
def state2(state):
  if state is np.nan:
    return "USA"
  else:
    return state

In [ ]:
df1["Location"] = df1["Location"].apply(state_USA)
df1.isnull().sum()
# df1.head()
df1["Geography"] = df1["Location"].apply(state)
# if df1['Location'] in USA_states_taken_from_WWW:
#   df1.Geography = df1.Geography.fillna('USA')
# else:
#   df1.Geography = df1.Geography.fillna('India')

In [ ]:
df[df["Geography"] == "USA"].shape[0]

3061

In [ ]:
df1.isnull().sum()

Deal_title                 0
Industry                   0
Deal_value                 0
Weighted_amount            0
Date_of_creation           0
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                  0
Location                   0
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         633
Internal_POC               0
Resource                 149
Internal_rating            0
Success_probability        0
dtype: int64

In [ ]:
#we see all missing region in usa area,so replacing it with mode of usa area
df2=df1[df1["Geography"]=="USA"]
df2.head()

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,Restaurants,320506.0,2067263.7,2020-03-29,Product_2,50 - 100 Million,Category 2,USA,TX,Executive Vice President,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",NaN,3,73.6
2,TitleFXSDN,Hospitals/Clinics,359392.0,2407926.4,2019-07-27,Product_1,500 Million - 1 Billion,Category 4,USA,NY,SVP/General Counsel,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Real Estate,76774.0,468321.4,2021-01-30,Product_2,500 Million - 1 Billion,Category 3,USA,WA,CEO/Co-Founder/Chairman,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
6,TitleOZQRY,Banks,384356.0,2709709.8,2019-11-20,Product_2,500 Million - 1 Billion,Category 1,USA,DE,CEO/Co-Founder/Chairman,Cartographer,Contact Email,Level 3,More than 2 weeks,"Booker,David L",NaN,4,73.4
7,TitleV05WV,Architecture/Engineering,245205.0,1642873.5,2020-12-22,Product_2,500 Million - 1 Billion,Category 1,USA,FL,Vice President / GM (04-present) : VP Sales an...,"Engineer, maintenance (IT)",Others,Level 2,5 days back,"Cashin,Marc C",No,5,74.1

In [ ]:
df1["Last_lead_update"] = df1["Last_lead_update"].fillna((df1.Last_lead_update.mode()[0]))

In [ ]:
df1["Resource"] = df1["Resource"].fillna((df1["Resource"].mode()[0]))

In [ ]:
df1.head()

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,Restaurants,320506.0,2.067264e+06,2020-03-29,Product_2,50 - 100 Million,Category 2,USA,TX,Executive Vice President,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",No,3,73.6
1,TitleKIW18,Construction Services,39488.0,2.408768e+05,2019-07-10,Product_2,500 Million - 1 Billion,Category 4,India,am,Chairman/CEO/President,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
2,TitleFXSDN,Hospitals/Clinics,359392.0,2.407926e+06,2019-07-27,Product_1,500 Million - 1 Billion,Category 4,USA,NY,SVP/General Counsel,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Real Estate,76774.0,4.683214e+05,2021-01-30,Product_2,500 Million - 1 Billion,Category 3,USA,WA,CEO/Co-Founder/Chairman,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
4,Title904GV,Financial Services,483896.0,1.569884e+06,2019-05-22,Product_2,50 - 100 Million,Category 3,India,ga,Executive Vice President,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [ ]:
df1.isna().sum()

Deal_title               0
Industry                 0
Deal_value               0
Weighted_amount          0
Date_of_creation         0
Pitch                    0
Lead_revenue             0
Fund_category            0
Geography                0
Location                 0
Designation              0
Hiring_candidate_role    0
Lead_source              0
Level_of_meeting         0
Last_lead_update         0
Internal_POC             0
Resource                 0
Internal_rating          0
Success_probability      0
dtype: int64

In [ ]:
df1.replace('?',np.nan,inplace=True)
df1.head()

,Deal_title,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,Restaurants,320506.0,2.067264e+06,2020-03-29,Product_2,50 - 100 Million,Category 2,USA,TX,Executive Vice President,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",No,3,73.6
1,TitleKIW18,Construction Services,39488.0,2.408768e+05,2019-07-10,Product_2,500 Million - 1 Billion,Category 4,India,am,Chairman/CEO/President,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
2,TitleFXSDN,Hospitals/Clinics,359392.0,2.407926e+06,2019-07-27,Product_1,500 Million - 1 Billion,Category 4,USA,NY,SVP/General Counsel,Health service manager,Marketing Event,Level 1,NaN,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Real Estate,76774.0,4.683214e+05,2021-01-30,Product_2,500 Million - 1 Billion,Category 3,USA,WA,CEO/Co-Founder/Chairman,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
4,Title904GV,Financial Services,483896.0,1.569884e+06,2019-05-22,Product_2,50 - 100 Million,Category 3,India,ga,Executive Vice President,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [ ]:
df1.to_csv('/content/gdrive/MyDrive/train_new.csv', index=False)